apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . | quote }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
         {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "helm.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.image.containerPort }}