apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.image.type }}
  ports:
    - port: {{ .Values.image.port }}
      targetPort: {{ .Values.image.targetPort }}
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}